# Generated by Django 4.1.6 on 2023-07-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Жанылык')),
                ('text', models.TextField(verbose_name='Жанылыктын мааниси')),
                ('image', models.ImageField(upload_to='images')),
                ('create_date', models.DateTimeField(verbose_name='Тузулган убакыты')),
                ('news_view', models.IntegerField(default=0, verbose_name='Коруучулар')),
            ],
            options={
                'verbose_name': 'Жанылык',
                'verbose_name_plural': 'Жанылыктар',
                'ordering': ('-create_date',),
            },
        ),
    ]
