# Generated by Django 4.0.4 on 2022-05-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('create_date', models.DateTimeField()),
                ('news_view', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('create_date',),
            },
        ),
    ]
