# Generated by Django 4.1.6 on 2023-07-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='I love my schoole')),
            ],
            options={
                'verbose_name': 'Коентария',
                'verbose_name_plural': 'Крментариялар',
            },
        ),
    ]
