# Generated by Django 4.1.5 on 2023-01-07 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="new",
            options={"ordering": ("-create_date",)},
        ),
    ]
