# Generated by Django 4.1.6 on 2023-07-07 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_class', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=None, max_length=10, null=True, verbose_name='Класс')),
                ('letter_class', models.CharField(choices=[('A', 'А'), ('Б', 'Б')], default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'класс кошуу',
                'verbose_name_plural': 'класстарды кошуу',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилиясы')),
                ('sub', models.CharField(max_length=250, verbose_name='Окутатурган сабагы')),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Мугалимдер',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('А', 'Аял'), ('Э', 'Эркек')], default=None, max_length=10, null=True, verbose_name='Жынысы')),
                ('first_name', models.CharField(max_length=250, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=250, verbose_name='Фамилиясы')),
                ('fathers_name', models.CharField(max_length=250, verbose_name='Атасынын аты')),
                ('mothers_name', models.CharField(max_length=250, verbose_name='Апасынын аты')),
                ('date_birth', models.DateField(verbose_name='туулган датасы')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='телефон')),
                ('l_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='home.list', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Окуучу',
                'verbose_name_plural': 'Окуучулар',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.list', verbose_name='Класс')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teachers', verbose_name='Класс жетекчиси')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класстар',
            },
        ),
    ]
