# Generated by Django 4.1.6 on 2023-07-07 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedcription', models.CharField(max_length=500, verbose_name='окуучу жонундо')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular', to='home.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'Активный студент',
                'verbose_name_plural': 'Активные студенты',
            },
        ),
    ]
