# Generated by Django 4.1.6 on 2023-07-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_popularstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default=1, upload_to='images/students'),
            preserve_default=False,
        ),
    ]
