# Generated by Django 4.0.4 on 2022-05-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teachers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdetail',
            options={'verbose_name_plural': 'Student list'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name_plural': 'Teachers list'},
        ),
        migrations.RenameField(
            model_name='studentdetail',
            old_name='dob',
            new_name='date_birth',
        ),
        migrations.AddField(
            model_name='teachers',
            name='sub',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
