# Generated by Django 4.0.4 on 2022-06-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_studentdetail_options_alter_teachers_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teachers')),
            ],
        ),
    ]
