# Generated by Django 4.0.4 on 2022-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
