# Generated by Django 4.0.4 on 2022-06-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_name_courses_child_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='classes',
        ),
        migrations.AlterField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.teachers'),
        ),
    ]
