# Generated by Django 4.0.5 on 2022-06-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_courses_classes_alter_courses_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='child_name',
        ),
        migrations.AddField(
            model_name='courses',
            name='std',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=None, max_length=10, null=True),
        ),
    ]
