# Generated by Django 4.0.5 on 2022-06-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_courses_child_name_courses_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='std',
            new_name='number_class',
        ),
    ]
