# Generated by Django 4.0.5 on 2022-06-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_courses_options_alter_studentdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_class', models.CharField(choices=[('a', 'а'), ('b', 'б')], default=None, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.abc'),
        ),
    ]
