# Generated by Django 3.2.9 on 2022-06-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_abc_courses_classes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetail',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='abc',
            name='letter_class',
            field=models.CharField(choices=[('а', 'а'), ('б', 'б')], default=None, max_length=10, null=True),
        ),
    ]
