# Generated by Django 4.0.4 on 2022-06-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_abc_options_alter_abc_letter_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.abc'),
        ),
    ]
