# Generated by Django 4.0.4 on 2022-06-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_std_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='std',
            new_name='list_class',
        ),
    ]
