# Generated by Django 4.0.4 on 2022-06-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='list_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='std_classes',
        ),
        migrations.AddField(
            model_name='list',
            name='letter_class',
            field=models.CharField(choices=[('A', 'А'), ('Б', 'Б')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='l_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.list'),
        ),
    ]
