# Generated by Django 4.0.4 on 2022-06-15 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_student_list_class_remove_student_std_classes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': 'класстар саны'},
        ),
        migrations.RemoveField(
            model_name='courses',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='number_class',
        ),
        migrations.AddField(
            model_name='courses',
            name='li_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.list'),
        ),
        migrations.DeleteModel(
            name='ABC',
        ),
    ]
