# Generated by Django 4.0.4 on 2022-06-15 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_list_options_remove_courses_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
