# Generated by Django 4.0.4 on 2022-06-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_courses_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='student',
        ),
        migrations.AddField(
            model_name='courses',
            name='student',
            field=models.ManyToManyField(to='home.student'),
        ),
    ]
