# Generated by Django 4.0.4 on 2022-06-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_courses_student_courses_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='student',
        ),
    ]
