# Generated by Django 3.2.8 on 2022-06-22 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_courses_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'verbose_name_plural': 'класстарды кошуу'},
        ),
    ]
