# Generated by Django 3.2.8 on 2022-06-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_list_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
