# Generated by Django 4.1.5 on 2023-01-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0023_student_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="list",
            options={"ordering": ["-id"], "verbose_name_plural": "класстарды кошуу"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["id"], "verbose_name_plural": "Окуучулар"},
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
